### ISSUE TITLE
gandalf-ssh should be able to send logs to stdout/stderr

### ISSUE THREAD

**Issue by saliceti** [tsuru/gandalf#198]
At the moment gandalf logs only to syslog.

This is an issue when we want to dockerise gandalf with https://github.com/tsuru/dockerized-setup because in this case we want the gandalf process inside the container to log to stdout (or stderr like in tsuru-api).
This would allow to read the logs via `docker logs gandalf` or configure docker to send the logs to another logging destination.

**Comment by fsouza** [comment]
@saliceti as Gandalf uses the same logging library as tsuru, just configuring it the same way we configure tsuru should be enough: http://docs.tsuru.io/en/stable/reference/config.html#logging

We should document it, though.

**Comment by saliceti** [comment]
Thanks this works fine for gandalf-web. I have used it in this PR: https://github.com/tsuru/dockerized-setup/pull/6

gandalf-ssh still logs to syslog though

**Comment by fsouza** [comment]
@saliceti this is definitely a bug in gandalf-ssh then :-(

I will mark this issue as a bug. Thanks!

**Comment by saliceti** [comment]
It would be nice to use the same logging library for gandalf-ssh, so we can write to file as well, add debug, etc.
